services:
  - type: web
    name: inventory-pro
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /home/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://inventory-pro-api-v2.onrender.com/api
