services:
  - type: web
    name: inventory-pro
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://inventory-pro-api-v2.onrender.com/api
