services:
  - type: web
    name: inventory-pro-api-v2
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://inventory-pro-api-v2.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: APP_KEY
        generateValue: true
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file